### ISSUE TITLE
Ben J's todo list for this weekend

### ISSUE THREAD

**Issue by benjaminpjones** [ELautzenhiser/gAImeCompetition#8]
### Functionality
- [x] Add QUIET
- [x] better errors from manager.py

### Refactor
- [ ] Beautify
- [x] Modularize run()
- [x] Use CDN instead of local url (and implement backup for when CDN is down.)
- [x] Generalize ace editor code

### Enhancements
- [x] Syntax Highlighting in Ace editors
- [x] More flexible arguments

**Comment by benjaminpjones** [comment]
All done except for beautify-ing the code.  That is more of a job for a linter (which I will look into finding a simple one!)
